service: ${env:LFW_SERVICE_CODE}
provider:
  name: aws
  stackName: ${env:LFW_TARGET_ENV_NAME}${self:service}
  runtime: nodejs12.x
  role: ${env:LFW_SLS_LAMBA_ROLE}
  stage: ${env:LFW_TARGET_ENV_NAME}
  service: ${env:LFW_SERVICE_CODE}
  region: ${env:LFW_TARGET_REGION}
  profile: ${env:LFW_AWS_PROFILE}
  deploymentBucket:
    name: ${env:LFW_SLS_BUCKET}
  environment:
    service: ${env:LFW_SERVICE_CODE}
    stage: ${env:LFW_TARGET_ENV_NAME}
    LFW_DB_CONNECTION: ${env:LFW_DB_CONNECTION}
  vpc:
    securityGroupIds:
      - ${env:LFW_VPN_SECURITY_GROUP}
    subnetIds:
      - ${env:LFW_SUBNET_1}
      - ${env:LFW_SUBNET_2}
package:
 exclude:
   - test
functions:
  ffoiProcess:
    name: ${env:LFW_TARGET_ENV_NAME}${self:service}-ffoiProcess
    handler: lib/functions/ffoi-process.handler
    timeout: 120
    memorySize: 2048
    reservedConcurrency: 20
  rloiProcess:
    name: ${env:LFW_TARGET_ENV_NAME}${self:service}-rloiProcess
    handler: lib/functions/rloi-process.handler
    timeout: 120
    memorySize: 2048
    reservedConcurrency: 20
  stationProcess:
    name: ${env:LFW_TARGET_ENV_NAME}${self:service}-stationProcess
    handler: lib/functions/station-process.handler
    timeout: 120
  rloiRefresh:
    name: ${env:LFW_TARGET_ENV_NAME}${self:service}-rloiRefresh
    handler: lib/functions/rloi-refresh.handler
    timeout: 60
  fwisProcess:
    name: ${env:LFW_TARGET_ENV_NAME}${self:service}-fwisProcess
    handler: lib/functions/fwis-process.handler
    timeout: 120
  fgsProcess:
    name: ${env:LFW_TARGET_ENV_NAME}${self:service}-fgsProcess
    handler: lib/functions/fgs-process.handler
    timeout: 60
